android.suppressUnsupportedCompileSdk=35
android.disallowKotlinSourceSets=false
# Improves project import performance for large projects
android.dependency.excludeLibraryComponentsFromConstraints=true
# Suppress sync issue warning
android.generateSyncIssueWhenLibraryConstraintsAreEnabled=false

# 16 KB page size support
android.useLegacyPackaging=false

android.useAndroidX=true
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.java.home=C:/src/PlayerID-Android/.local-jdks/jdk-17.0.18+8
kotlin.version=1.9.0
